#ifndef _TESTCOMP_IDL_
#define _TESTCOMP_IDL_

#include <baci.idl>

module TEST
{	
	interface testComp : ACS::CharacteristicComponent
	{
		/*Properties*/

		readonly attribute ACS::ROdouble testProp;

		/*Actions*/
	};
};

#endif //_TESTCOMP_IDL_

