/**
 */
package baciCodeGen.BACIProperties.provider;

import baciCodeGen.BACIProperties.util.BACIPropertiesAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BACIPropertiesItemProviderAdapterFactory extends BACIPropertiesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BACIPropertiesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.CharacteristicComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CharacteristicComponentItemProvider characteristicComponentItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.CharacteristicComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCharacteristicComponentAdapter() {
		if (characteristicComponentItemProvider == null) {
			characteristicComponentItemProvider = new CharacteristicComponentItemProvider(this);
		}

		return characteristicComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.CharacteristicModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CharacteristicModelItemProvider characteristicModelItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.CharacteristicModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCharacteristicModelAdapter() {
		if (characteristicModelItemProvider == null) {
			characteristicModelItemProvider = new CharacteristicModelItemProvider(this);
		}

		return characteristicModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pboolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PbooleanItemProvider pbooleanItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pboolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPbooleanAdapter() {
		if (pbooleanItemProvider == null) {
			pbooleanItemProvider = new PbooleanItemProvider(this);
		}

		return pbooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pboolean1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Pboolean1ItemProvider pboolean1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pboolean1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPboolean1Adapter() {
		if (pboolean1ItemProvider == null) {
			pboolean1ItemProvider = new Pboolean1ItemProvider(this);
		}

		return pboolean1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PbooleanSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PbooleanSeqItemProvider pbooleanSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PbooleanSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPbooleanSeqAdapter() {
		if (pbooleanSeqItemProvider == null) {
			pbooleanSeqItemProvider = new PbooleanSeqItemProvider(this);
		}

		return pbooleanSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PbooleanSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PbooleanSeq1ItemProvider pbooleanSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PbooleanSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPbooleanSeq1Adapter() {
		if (pbooleanSeq1ItemProvider == null) {
			pbooleanSeq1ItemProvider = new PbooleanSeq1ItemProvider(this);
		}

		return pbooleanSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pdouble} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PdoubleItemProvider pdoubleItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pdouble}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPdoubleAdapter() {
		if (pdoubleItemProvider == null) {
			pdoubleItemProvider = new PdoubleItemProvider(this);
		}

		return pdoubleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pdouble1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Pdouble1ItemProvider pdouble1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pdouble1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPdouble1Adapter() {
		if (pdouble1ItemProvider == null) {
			pdouble1ItemProvider = new Pdouble1ItemProvider(this);
		}

		return pdouble1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PdoubleSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PdoubleSeqItemProvider pdoubleSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PdoubleSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPdoubleSeqAdapter() {
		if (pdoubleSeqItemProvider == null) {
			pdoubleSeqItemProvider = new PdoubleSeqItemProvider(this);
		}

		return pdoubleSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PdoubleSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PdoubleSeq1ItemProvider pdoubleSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PdoubleSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPdoubleSeq1Adapter() {
		if (pdoubleSeq1ItemProvider == null) {
			pdoubleSeq1ItemProvider = new PdoubleSeq1ItemProvider(this);
		}

		return pdoubleSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PEnum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PEnumItemProvider pEnumItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PEnum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPEnumAdapter() {
		if (pEnumItemProvider == null) {
			pEnumItemProvider = new PEnumItemProvider(this);
		}

		return pEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PEnum1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PEnum1ItemProvider pEnum1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PEnum1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPEnum1Adapter() {
		if (pEnum1ItemProvider == null) {
			pEnum1ItemProvider = new PEnum1ItemProvider(this);
		}

		return pEnum1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pfloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PfloatItemProvider pfloatItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pfloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPfloatAdapter() {
		if (pfloatItemProvider == null) {
			pfloatItemProvider = new PfloatItemProvider(this);
		}

		return pfloatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pfloat1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Pfloat1ItemProvider pfloat1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pfloat1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPfloat1Adapter() {
		if (pfloat1ItemProvider == null) {
			pfloat1ItemProvider = new Pfloat1ItemProvider(this);
		}

		return pfloat1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PfloatSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PfloatSeqItemProvider pfloatSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PfloatSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPfloatSeqAdapter() {
		if (pfloatSeqItemProvider == null) {
			pfloatSeqItemProvider = new PfloatSeqItemProvider(this);
		}

		return pfloatSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PfloatSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PfloatSeq1ItemProvider pfloatSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PfloatSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPfloatSeq1Adapter() {
		if (pfloatSeq1ItemProvider == null) {
			pfloatSeq1ItemProvider = new PfloatSeq1ItemProvider(this);
		}

		return pfloatSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Plong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlongItemProvider plongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Plong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlongAdapter() {
		if (plongItemProvider == null) {
			plongItemProvider = new PlongItemProvider(this);
		}

		return plongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Plong1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Plong1ItemProvider plong1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Plong1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlong1Adapter() {
		if (plong1ItemProvider == null) {
			plong1ItemProvider = new Plong1ItemProvider(this);
		}

		return plong1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PlongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlongLongItemProvider plongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PlongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlongLongAdapter() {
		if (plongLongItemProvider == null) {
			plongLongItemProvider = new PlongLongItemProvider(this);
		}

		return plongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PlongLong1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlongLong1ItemProvider plongLong1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PlongLong1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlongLong1Adapter() {
		if (plongLong1ItemProvider == null) {
			plongLong1ItemProvider = new PlongLong1ItemProvider(this);
		}

		return plongLong1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PlongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlongSeqItemProvider plongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PlongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlongSeqAdapter() {
		if (plongSeqItemProvider == null) {
			plongSeqItemProvider = new PlongSeqItemProvider(this);
		}

		return plongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PlongSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlongSeq1ItemProvider plongSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PlongSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlongSeq1Adapter() {
		if (plongSeq1ItemProvider == null) {
			plongSeq1ItemProvider = new PlongSeq1ItemProvider(this);
		}

		return plongSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Ppattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PpatternItemProvider ppatternItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Ppattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPpatternAdapter() {
		if (ppatternItemProvider == null) {
			ppatternItemProvider = new PpatternItemProvider(this);
		}

		return ppatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Ppattern1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Ppattern1ItemProvider ppattern1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Ppattern1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPpattern1Adapter() {
		if (ppattern1ItemProvider == null) {
			ppattern1ItemProvider = new Ppattern1ItemProvider(this);
		}

		return ppattern1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pstring} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PstringItemProvider pstringItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pstring}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPstringAdapter() {
		if (pstringItemProvider == null) {
			pstringItemProvider = new PstringItemProvider(this);
		}

		return pstringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.Pstring1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Pstring1ItemProvider pstring1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.Pstring1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPstring1Adapter() {
		if (pstring1ItemProvider == null) {
			pstring1ItemProvider = new Pstring1ItemProvider(this);
		}

		return pstring1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PstringSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PstringSeqItemProvider pstringSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PstringSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPstringSeqAdapter() {
		if (pstringSeqItemProvider == null) {
			pstringSeqItemProvider = new PstringSeqItemProvider(this);
		}

		return pstringSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PstringSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PstringSeq1ItemProvider pstringSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PstringSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPstringSeq1Adapter() {
		if (pstringSeq1ItemProvider == null) {
			pstringSeq1ItemProvider = new PstringSeq1ItemProvider(this);
		}

		return pstringSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLongItemProvider puLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLongAdapter() {
		if (puLongItemProvider == null) {
			puLongItemProvider = new PuLongItemProvider(this);
		}

		return puLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLong1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLong1ItemProvider puLong1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLong1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLong1Adapter() {
		if (puLong1ItemProvider == null) {
			puLong1ItemProvider = new PuLong1ItemProvider(this);
		}

		return puLong1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLongLongItemProvider puLongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLongLongAdapter() {
		if (puLongLongItemProvider == null) {
			puLongLongItemProvider = new PuLongLongItemProvider(this);
		}

		return puLongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLongLong1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLongLong1ItemProvider puLongLong1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLongLong1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLongLong1Adapter() {
		if (puLongLong1ItemProvider == null) {
			puLongLong1ItemProvider = new PuLongLong1ItemProvider(this);
		}

		return puLongLong1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLongSeqItemProvider puLongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLongSeqAdapter() {
		if (puLongSeqItemProvider == null) {
			puLongSeqItemProvider = new PuLongSeqItemProvider(this);
		}

		return puLongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.PuLongSeq1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PuLongSeq1ItemProvider puLongSeq1ItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.PuLongSeq1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPuLongSeq1Adapter() {
		if (puLongSeq1ItemProvider == null) {
			puLongSeq1ItemProvider = new PuLongSeq1ItemProvider(this);
		}

		return puLongSeq1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROboolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RObooleanItemProvider rObooleanItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROboolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRObooleanAdapter() {
		if (rObooleanItemProvider == null) {
			rObooleanItemProvider = new RObooleanItemProvider(this);
		}

		return rObooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RObooleanSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RObooleanSeqItemProvider rObooleanSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RObooleanSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRObooleanSeqAdapter() {
		if (rObooleanSeqItemProvider == null) {
			rObooleanSeqItemProvider = new RObooleanSeqItemProvider(this);
		}

		return rObooleanSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROdouble} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROdoubleItemProvider rOdoubleItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROdouble}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROdoubleAdapter() {
		if (rOdoubleItemProvider == null) {
			rOdoubleItemProvider = new ROdoubleItemProvider(this);
		}

		return rOdoubleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROdoubleSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROdoubleSeqItemProvider rOdoubleSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROdoubleSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROdoubleSeqAdapter() {
		if (rOdoubleSeqItemProvider == null) {
			rOdoubleSeqItemProvider = new ROdoubleSeqItemProvider(this);
		}

		return rOdoubleSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROEnum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROEnumItemProvider roEnumItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROEnum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROEnumAdapter() {
		if (roEnumItemProvider == null) {
			roEnumItemProvider = new ROEnumItemProvider(this);
		}

		return roEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROfloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROfloatItemProvider rOfloatItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROfloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROfloatAdapter() {
		if (rOfloatItemProvider == null) {
			rOfloatItemProvider = new ROfloatItemProvider(this);
		}

		return rOfloatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROfloatSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROfloatSeqItemProvider rOfloatSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROfloatSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROfloatSeqAdapter() {
		if (rOfloatSeqItemProvider == null) {
			rOfloatSeqItemProvider = new ROfloatSeqItemProvider(this);
		}

		return rOfloatSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROlong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROlongItemProvider rOlongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROlong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROlongAdapter() {
		if (rOlongItemProvider == null) {
			rOlongItemProvider = new ROlongItemProvider(this);
		}

		return rOlongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROlongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROlongLongItemProvider rOlongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROlongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROlongLongAdapter() {
		if (rOlongLongItemProvider == null) {
			rOlongLongItemProvider = new ROlongLongItemProvider(this);
		}

		return rOlongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROlongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROlongSeqItemProvider rOlongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROlongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROlongSeqAdapter() {
		if (rOlongSeqItemProvider == null) {
			rOlongSeqItemProvider = new ROlongSeqItemProvider(this);
		}

		return rOlongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROpattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROpatternItemProvider rOpatternItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROpattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROpatternAdapter() {
		if (rOpatternItemProvider == null) {
			rOpatternItemProvider = new ROpatternItemProvider(this);
		}

		return rOpatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROstring} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROstringItemProvider rOstringItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROstring}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROstringAdapter() {
		if (rOstringItemProvider == null) {
			rOstringItemProvider = new ROstringItemProvider(this);
		}

		return rOstringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROstringSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROstringSeqItemProvider rOstringSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROstringSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROstringSeqAdapter() {
		if (rOstringSeqItemProvider == null) {
			rOstringSeqItemProvider = new ROstringSeqItemProvider(this);
		}

		return rOstringSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROuLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROuLongItemProvider rOuLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROuLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROuLongAdapter() {
		if (rOuLongItemProvider == null) {
			rOuLongItemProvider = new ROuLongItemProvider(this);
		}

		return rOuLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROuLongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROuLongLongItemProvider rOuLongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROuLongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROuLongLongAdapter() {
		if (rOuLongLongItemProvider == null) {
			rOuLongLongItemProvider = new ROuLongLongItemProvider(this);
		}

		return rOuLongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.ROuLongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ROuLongSeqItemProvider rOuLongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.ROuLongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createROuLongSeqAdapter() {
		if (rOuLongSeqItemProvider == null) {
			rOuLongSeqItemProvider = new ROuLongSeqItemProvider(this);
		}

		return rOuLongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWboolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWbooleanItemProvider rWbooleanItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWboolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWbooleanAdapter() {
		if (rWbooleanItemProvider == null) {
			rWbooleanItemProvider = new RWbooleanItemProvider(this);
		}

		return rWbooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWbooleanSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWbooleanSeqItemProvider rWbooleanSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWbooleanSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWbooleanSeqAdapter() {
		if (rWbooleanSeqItemProvider == null) {
			rWbooleanSeqItemProvider = new RWbooleanSeqItemProvider(this);
		}

		return rWbooleanSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWdouble} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWdoubleItemProvider rWdoubleItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWdouble}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWdoubleAdapter() {
		if (rWdoubleItemProvider == null) {
			rWdoubleItemProvider = new RWdoubleItemProvider(this);
		}

		return rWdoubleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWdoubleSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWdoubleSeqItemProvider rWdoubleSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWdoubleSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWdoubleSeqAdapter() {
		if (rWdoubleSeqItemProvider == null) {
			rWdoubleSeqItemProvider = new RWdoubleSeqItemProvider(this);
		}

		return rWdoubleSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWEnum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWEnumItemProvider rwEnumItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWEnum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWEnumAdapter() {
		if (rwEnumItemProvider == null) {
			rwEnumItemProvider = new RWEnumItemProvider(this);
		}

		return rwEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWfloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWfloatItemProvider rWfloatItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWfloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWfloatAdapter() {
		if (rWfloatItemProvider == null) {
			rWfloatItemProvider = new RWfloatItemProvider(this);
		}

		return rWfloatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWfloatSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWfloatSeqItemProvider rWfloatSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWfloatSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWfloatSeqAdapter() {
		if (rWfloatSeqItemProvider == null) {
			rWfloatSeqItemProvider = new RWfloatSeqItemProvider(this);
		}

		return rWfloatSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWlong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWlongItemProvider rWlongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWlong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWlongAdapter() {
		if (rWlongItemProvider == null) {
			rWlongItemProvider = new RWlongItemProvider(this);
		}

		return rWlongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWlongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWlongLongItemProvider rWlongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWlongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWlongLongAdapter() {
		if (rWlongLongItemProvider == null) {
			rWlongLongItemProvider = new RWlongLongItemProvider(this);
		}

		return rWlongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWlongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWlongSeqItemProvider rWlongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWlongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWlongSeqAdapter() {
		if (rWlongSeqItemProvider == null) {
			rWlongSeqItemProvider = new RWlongSeqItemProvider(this);
		}

		return rWlongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWpattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWpatternItemProvider rWpatternItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWpattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWpatternAdapter() {
		if (rWpatternItemProvider == null) {
			rWpatternItemProvider = new RWpatternItemProvider(this);
		}

		return rWpatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWstring} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWstringItemProvider rWstringItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWstring}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWstringAdapter() {
		if (rWstringItemProvider == null) {
			rWstringItemProvider = new RWstringItemProvider(this);
		}

		return rWstringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWuLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWuLongItemProvider rWuLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWuLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWuLongAdapter() {
		if (rWuLongItemProvider == null) {
			rWuLongItemProvider = new RWuLongItemProvider(this);
		}

		return rWuLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWuLongLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWuLongLongItemProvider rWuLongLongItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWuLongLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWuLongLongAdapter() {
		if (rWuLongLongItemProvider == null) {
			rWuLongLongItemProvider = new RWuLongLongItemProvider(this);
		}

		return rWuLongLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.RWuLongSeq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RWuLongSeqItemProvider rWuLongSeqItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.RWuLongSeq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRWuLongSeqAdapter() {
		if (rWuLongSeqItemProvider == null) {
			rWuLongSeqItemProvider = new RWuLongSeqItemProvider(this);
		}

		return rWuLongSeqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link baciCodeGen.BACIProperties.TypelessProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypelessPropertyItemProvider typelessPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link baciCodeGen.BACIProperties.TypelessProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypelessPropertyAdapter() {
		if (typelessPropertyItemProvider == null) {
			typelessPropertyItemProvider = new TypelessPropertyItemProvider(this);
		}

		return typelessPropertyItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (characteristicComponentItemProvider != null) characteristicComponentItemProvider.dispose();
		if (characteristicModelItemProvider != null) characteristicModelItemProvider.dispose();
		if (pbooleanItemProvider != null) pbooleanItemProvider.dispose();
		if (pboolean1ItemProvider != null) pboolean1ItemProvider.dispose();
		if (pbooleanSeqItemProvider != null) pbooleanSeqItemProvider.dispose();
		if (pbooleanSeq1ItemProvider != null) pbooleanSeq1ItemProvider.dispose();
		if (pdoubleItemProvider != null) pdoubleItemProvider.dispose();
		if (pdouble1ItemProvider != null) pdouble1ItemProvider.dispose();
		if (pdoubleSeqItemProvider != null) pdoubleSeqItemProvider.dispose();
		if (pdoubleSeq1ItemProvider != null) pdoubleSeq1ItemProvider.dispose();
		if (pEnumItemProvider != null) pEnumItemProvider.dispose();
		if (pEnum1ItemProvider != null) pEnum1ItemProvider.dispose();
		if (pfloatItemProvider != null) pfloatItemProvider.dispose();
		if (pfloat1ItemProvider != null) pfloat1ItemProvider.dispose();
		if (pfloatSeqItemProvider != null) pfloatSeqItemProvider.dispose();
		if (pfloatSeq1ItemProvider != null) pfloatSeq1ItemProvider.dispose();
		if (plongItemProvider != null) plongItemProvider.dispose();
		if (plong1ItemProvider != null) plong1ItemProvider.dispose();
		if (plongLongItemProvider != null) plongLongItemProvider.dispose();
		if (plongLong1ItemProvider != null) plongLong1ItemProvider.dispose();
		if (plongSeqItemProvider != null) plongSeqItemProvider.dispose();
		if (plongSeq1ItemProvider != null) plongSeq1ItemProvider.dispose();
		if (ppatternItemProvider != null) ppatternItemProvider.dispose();
		if (ppattern1ItemProvider != null) ppattern1ItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (pstringItemProvider != null) pstringItemProvider.dispose();
		if (pstring1ItemProvider != null) pstring1ItemProvider.dispose();
		if (pstringSeqItemProvider != null) pstringSeqItemProvider.dispose();
		if (pstringSeq1ItemProvider != null) pstringSeq1ItemProvider.dispose();
		if (puLongItemProvider != null) puLongItemProvider.dispose();
		if (puLong1ItemProvider != null) puLong1ItemProvider.dispose();
		if (puLongLongItemProvider != null) puLongLongItemProvider.dispose();
		if (puLongLong1ItemProvider != null) puLongLong1ItemProvider.dispose();
		if (puLongSeqItemProvider != null) puLongSeqItemProvider.dispose();
		if (puLongSeq1ItemProvider != null) puLongSeq1ItemProvider.dispose();
		if (rObooleanItemProvider != null) rObooleanItemProvider.dispose();
		if (rObooleanSeqItemProvider != null) rObooleanSeqItemProvider.dispose();
		if (rOdoubleItemProvider != null) rOdoubleItemProvider.dispose();
		if (rOdoubleSeqItemProvider != null) rOdoubleSeqItemProvider.dispose();
		if (roEnumItemProvider != null) roEnumItemProvider.dispose();
		if (rOfloatItemProvider != null) rOfloatItemProvider.dispose();
		if (rOfloatSeqItemProvider != null) rOfloatSeqItemProvider.dispose();
		if (rOlongItemProvider != null) rOlongItemProvider.dispose();
		if (rOlongLongItemProvider != null) rOlongLongItemProvider.dispose();
		if (rOlongSeqItemProvider != null) rOlongSeqItemProvider.dispose();
		if (rOpatternItemProvider != null) rOpatternItemProvider.dispose();
		if (rOstringItemProvider != null) rOstringItemProvider.dispose();
		if (rOstringSeqItemProvider != null) rOstringSeqItemProvider.dispose();
		if (rOuLongItemProvider != null) rOuLongItemProvider.dispose();
		if (rOuLongLongItemProvider != null) rOuLongLongItemProvider.dispose();
		if (rOuLongSeqItemProvider != null) rOuLongSeqItemProvider.dispose();
		if (rWbooleanItemProvider != null) rWbooleanItemProvider.dispose();
		if (rWbooleanSeqItemProvider != null) rWbooleanSeqItemProvider.dispose();
		if (rWdoubleItemProvider != null) rWdoubleItemProvider.dispose();
		if (rWdoubleSeqItemProvider != null) rWdoubleSeqItemProvider.dispose();
		if (rwEnumItemProvider != null) rwEnumItemProvider.dispose();
		if (rWfloatItemProvider != null) rWfloatItemProvider.dispose();
		if (rWfloatSeqItemProvider != null) rWfloatSeqItemProvider.dispose();
		if (rWlongItemProvider != null) rWlongItemProvider.dispose();
		if (rWlongLongItemProvider != null) rWlongLongItemProvider.dispose();
		if (rWlongSeqItemProvider != null) rWlongSeqItemProvider.dispose();
		if (rWpatternItemProvider != null) rWpatternItemProvider.dispose();
		if (rWstringItemProvider != null) rWstringItemProvider.dispose();
		if (rWuLongItemProvider != null) rWuLongItemProvider.dispose();
		if (rWuLongLongItemProvider != null) rWuLongLongItemProvider.dispose();
		if (rWuLongSeqItemProvider != null) rWuLongSeqItemProvider.dispose();
		if (typelessPropertyItemProvider != null) typelessPropertyItemProvider.dispose();
	}

}
